<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration: create_penjualan_tables
 *
 * Creates two related tables in a single migration to keep the sales
 * transaction header and its line items together:
 *
 *   1. penjualan        — Sales order header (one record per transaction)
 *   2. penjualan_detail — Sales order line items (one record per product/row)
 *
 * Key design decisions:
 *   - penjualan is scoped by toko_id for multi-tenant isolation.
 *   - nomor_invoice is globally UNIQUE — auto-generated by the application
 *     (e.g., INV/20260101/0001) to guarantee uniqueness across all tenants.
 *   - pelanggan_id is nullable to support walk-in / anonymous customers
 *     (status_pelanggan = 'Umum') without requiring a customer record.
 *   - diskon is stored at header level for simplicity; item-level discounts
 *     can be added as a future enhancement.
 *   - nominal_uang = cash tendered; kembalian = change returned.
 *   - 'Digital Payment' covers QRIS, e-wallets, EDC debit, etc.
 *   - status_pembayaran 'Belum Lunas' supports credit sales tracking.
 *   - penjualan_detail.produk_id intentionally does NOT cascade delete;
 *     sold products must remain traceable in historical reports.
 *
 * Execution Order : 10 of 11
 * Database        : db_retail_mini_erp
 *
 * Foreign Keys (penjualan):
 *   - toko_id      → toko(id)       ON DELETE CASCADE
 *   - pelanggan_id → pelanggan(id)  (nullable)
 *   - user_id      → users(id)
 *
 * Foreign Keys (penjualan_detail):
 *   - penjualan_id → penjualan(id)  ON DELETE CASCADE
 *   - produk_id    → produk(id)
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // ─── Sales Header ───────────────────────────────────────────────────
        Schema::create('penjualan', function (Blueprint $table) {
            $table->id();
            $table->foreignId('toko_id')->constrained('toko')->onDelete('cascade');
            $table->foreignId('pelanggan_id')->nullable()->constrained('pelanggan');
            $table->string('nomor_invoice', 50)->unique();
            $table->decimal('total_harga', 12, 2);
            $table->decimal('diskon', 12, 2)->default(0);
            $table->decimal('total_bayar', 12, 2);
            $table->decimal('nominal_uang', 12, 2)->default(0);
            $table->decimal('kembalian', 12, 2)->default(0);
            $table->enum('metode_pembayaran', ['Tunai', 'Kredit', 'Digital Payment']);
            $table->enum('status_pembayaran', ['Lunas', 'Belum Lunas']);
            $table->foreignId('user_id')->constrained('users');
            $table->timestamps();
        });

        // ─── Sales Line Items ────────────────────────────────────────────────
        Schema::create('penjualan_detail', function (Blueprint $table) {
            $table->id();
            $table->foreignId('penjualan_id')->constrained('penjualan')->onDelete('cascade');
            $table->foreignId('produk_id')->constrained('produk');
            $table->decimal('harga_satuan', 12, 2);
            $table->integer('qty');
            $table->decimal('subtotal', 12, 2);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * Must drop detail table first due to FK constraint on penjualan_id.
     */
    public function down(): void
    {
        Schema::dropIfExists('penjualan_detail');
        Schema::dropIfExists('penjualan');
    }
};
