<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Model: Penjualan
 *
 * Sales transaction header — one record per POS transaction (invoice).
 * Scoped per tenant (toko_id).
 *
 * Business Automation (handled by PenjualanController@store):
 *   1. On submit → decrement produk.stok for each line item.
 *   2. On submit → insert row into log_stok (tipe = 'Penjualan').
 *   3. If metode_pembayaran = 'Tunai' → insert arus_kas (tipe = 'Masuk', kategori = 'Penjualan').
 *   4. If metode_pembayaran = 'Kredit' → set status_pembayaran = 'Belum Lunas' (piutang).
 *
 * Backend Price Validation (PRD Pasal 5):
 *   The controller MUST re-validate harga_satuan from the client against
 *   produk.getHargaByStatus(pelanggan.status_pelanggan) before persisting.
 *
 * nomor_invoice is globally UNIQUE — auto-generated by the application
 * (format: INV/YYYYMMDD/XXXX) — not submitted by the client.
 *
 * pelanggan_id is nullable — walk-in "Umum" customers need no customer record.
 *
 * Global Scope: Auto-filters queries by authenticated user's toko_id.
 *
 * @property int         $id
 * @property int         $toko_id
 * @property int|null    $pelanggan_id
 * @property string      $nomor_invoice
 * @property float       $total_harga
 * @property float       $diskon
 * @property float       $total_bayar
 * @property float       $nominal_uang
 * @property float       $kembalian
 * @property string      $metode_pembayaran  Tunai|Kredit|Digital Payment
 * @property string      $status_pembayaran  Lunas|Belum Lunas
 * @property int         $user_id
 */
class Penjualan extends Model
{
    /**
     * The table associated with the model.
     */
    protected $table = 'penjualan';

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'toko_id',
        'pelanggan_id',
        'nomor_invoice',
        'total_harga',
        'diskon',
        'total_bayar',
        'nominal_uang',
        'kembalian',
        'metode_pembayaran',
        'status_pembayaran',
        'user_id',
        'uang_muka',
        'sisa_piutang',
        'tanggal_jatuh_tempo',
    ];

    /**
     * The attributes that should be cast to native types.
     */
    protected $casts = [
        'total_harga'         => 'decimal:2',
        'diskon'              => 'decimal:2',
        'total_bayar'         => 'decimal:2',
        'nominal_uang'        => 'decimal:2',
        'kembalian'           => 'decimal:2',
        'uang_muka'           => 'decimal:2',
        'sisa_piutang'        => 'decimal:2',
        'tanggal_jatuh_tempo' => 'date',
    ];

    /**
     * Boot the model.
     * Registers the tenant Global Scope and auto-assigns toko_id on creation.
     */
    protected static function booted(): void
    {
        // ── Global Scope: auto-filter by the authenticated tenant ──────────
        static::addGlobalScope('tenant', function (Builder $builder) {
            if (auth()->check()) {
                $builder->where('penjualan.toko_id', auth()->user()->toko_id);
            }
        });

        // ── Creating Event: auto-assign toko_id from the logged-in user ───
        static::creating(function (self $model) {
            if (auth()->check() && empty($model->toko_id)) {
                $model->toko_id = auth()->user()->toko_id;
            }
        });
    }

    // ─── Relationships ──────────────────────────────────────────────────────

    /**
     * A sale belongs to one toko (tenant).
     */
    public function toko(): BelongsTo
    {
        return $this->belongsTo(Toko::class, 'toko_id');
    }

    /**
     * A sale may belong to a named customer (nullable — walk-ins have null).
     */
    public function pelanggan(): BelongsTo
    {
        return $this->belongsTo(Pelanggan::class, 'pelanggan_id');
    }

    /**
     * A sale is processed by one kasir/user.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * A sale has many line items (product rows).
     */
    public function details(): HasMany
    {
        return $this->hasMany(PenjualanDetail::class, 'penjualan_id');
    }

    /**
     * A sale can have many partial payments (cicilan kredit).
     */
    public function pembayaranKredit(): HasMany
    {
        return $this->hasMany(PembayaranKredit::class, 'penjualan_id')->orderBy('tanggal_bayar');
    }

    // ─── Helper Methods ─────────────────────────────────────────────────────

    /**
     * Check whether this sale is a credit transaction (piutang).
     */
    public function isKredit(): bool
    {
        return $this->metode_pembayaran === 'Kredit';
    }

    /**
     * Check whether this sale is fully paid.
     */
    public function isLunas(): bool
    {
        return $this->status_pembayaran === 'Lunas';
    }

    /**
     * Generate a unique nomor_invoice in the format INV/YYYYMMDD/XXXX.
     * Call this from PenjualanController before creating the record.
     */
    public static function generateNomorInvoice(): string
    {
        $prefix = 'INV/' . now()->format('Ymd') . '/';
        $last   = static::withoutGlobalScope('tenant')
            ->where('nomor_invoice', 'like', $prefix . '%')
            ->orderByDesc('id')
            ->value('nomor_invoice');

        $sequence = $last ? (int) substr($last, -4) + 1 : 1;

        return $prefix . str_pad($sequence, 4, '0', STR_PAD_LEFT);
    }
}
